objects/Account.object
<CustomObject>
    <fields>
        <fullName>SBQQ__AssetQuantitiesCombined__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Option to combine quantities of multiple assets for the same product into one line when renewal quote is generated.</description>
        <inlineHelpText>Option to combine quantities of multiple assets for the same product into one line when renewal quote is generated.</inlineHelpText>
        <label>Combine Asset Quantities</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__CoTermedContractsCombined__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag that controls whether assets and subscriptions from multiple co-teremed contracts are rolled up together. By default, each co-termed contract generates a separate group on renewal quote.</description>
        <inlineHelpText>Enable to combine assets and subscriptions from multiple co-termed contracts. By default, each co-termed contract generates a separate group on renewal quote.</inlineHelpText>
        <label>Combine Co-Termed Contracts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__CoTerminationEvent__c</fullName>
        <description>Determines when contracts are co-terminated.</description>
        <inlineHelpText>Determines when contracts are co-terminated.</inlineHelpText>
        <label>Co-Termination Event</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SBQQ__ContractCoTermination__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Add-on</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__ContractCoTermination__c</fullName>
        <description>Determines how service and subscription contracts for this customer are co-terminated.</description>
        <inlineHelpText>Determines how service and subscription contracts for this customer are co-terminated.</inlineHelpText>
        <label>Contract Co-Termination</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Never</fullName>
                    <default>true</default>
                    <label>Never</label>
                </value>
                <value>
                    <fullName>Always</fullName>
                </value>
                <value>
                    <fullName>Prompt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalModel__c</fullName>
        <description>The option to distinguish between Subscription or Asset based renewal.</description>
        <inlineHelpText>Choose Asset Based to make renewals based off of an account&apos;s Assets or choose Subscription based to makes renewals based off of subscriptions created from a quote.</inlineHelpText>
        <label>Renewal Model</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Based</fullName>
                </value>
                <value>
                    <fullName>Contract Based</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalPricingMethod__c</fullName>
        <description>Method for pricing products on renewal.</description>
        <inlineHelpText>Use &quot;Same&quot; to keep the same price paid last time. Use &quot;List&quot; to use current list price. Use &quot;Uplift&quot; to use the price paid last time plus some uplift.</inlineHelpText>
        <label>Renewal Pricing Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Same</fullName>
                    <default>true</default>
                    <label>Same</label>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Uplift</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this asset.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Asset</fullName>
        <active>true</active>
        <description>For all standard Assets.</description>
        <label>Asset</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote line where this order product is created from.</description>
        <inlineHelpText>The quote line where this order product is created from.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>OrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Q2C_Demo_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Master_Quote__c</fullName>
        <label>Master Quote (Record ID)</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Q2C Demo Settings</label>
</CustomObject>

objects/SBQQ__ContractedPrice__c.object
<CustomObject>
    <customHelpPage>SBQQ__ContractedPriceHelp</customHelpPage>
    <description>Contracted (negotiated) price for a product for a given customer account.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <description>Account for which this price was negotiated.</description>
        <inlineHelpText>Account for which this price was negotiated.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracted Prices</relationshipLabel>
        <relationshipName>R00N70000001olI5EAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contracted Price</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Contracted Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracted Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__DiscountSchedule__c.object
<CustomObject>
    <customHelpPage>SBQQ__DiscountScheduleHelp</customHelpPage>
    <description>Volume discount schedule that applies automatic discounts based on quantity.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that this discount schedule applies to. Only used in combination with Discount Schedule Override on Quote Line Editor UI.</description>
        <inlineHelpText>Account that this discount schedule applies to. Only used in combination with Discount Schedule Override on Quote Line Editor UI.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Discount Schedules</relationshipLabel>
        <relationshipName>Discount_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote Line that this discount schedule applies to. Only used in combination with Discount Schedule Override on Quote Line Editor UI.</description>
        <inlineHelpText>Quote Line that this discount schedule applies to. Only used in combination with Discount Schedule Override on Quote Line Editor UI.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Discount Schedules</relationshipLabel>
        <relationshipName>Discount_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote that this discount schedule applies to. Only used in combination with Discount Schedule Override on Quote Line Editor UI.</description>
        <inlineHelpText>Quote that this discount schedule applies to. Only used in combination with Discount Schedule Override on Quote Line Editor UI.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Discount Schedules</relationshipLabel>
        <relationshipName>Discount_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discount Schedule</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discount Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
        <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
        <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>The first date this subscription is in effect.</description>
        <formula>if ( ISBLANK (SBQQ__SubscriptionStartDate__c), SBQQ__Contract__r.StartDate, SBQQ__SubscriptionStartDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The first date this subscription is in effect.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Q2CAccountUtilitiesController.cls
public without sharing class Q2CAccountUtilitiesController {

    public Q2C_Demo_Settings__c settings { get; set; }
    public Id AccountId { get; set; }
    public Account ThisAccount { get; set; }
    public Contact ThisContact { get; set; }
    private ApexPages.StandardController Controller;
    private Id[] QuotesToDelete;

    //CONSTRUCTOR for VF Pages
    public Q2CAccountUtilitiesController(ApexPages.StandardController stdController) {
        this.AccountId = stdController.getId();
        Id acctId = this.AccountId;
        ThisAccount = [SELECT SBQQ__CoTermedContractsCombined__c, SBQQ__AssetQuantitiesCombined__c, SBQQ__RenewalModel__c,SBQQ__ContractCoTermination__c, ShippingAddress, BillingAddress,SBQQ__CoTerminationEvent__c,SBQQ__RenewalPricingMethod__c FROM Account where Id = :acctId];
        this.Controller = stdController;
        settings = Q2C_Demo_Settings__c.getOrgDefaults();
        IF([SELECT Id, FirstName, LastName, Email FROM Contact WHERE AccountId = :acctId LIMIT 1].size()>0){
            ThisContact = [SELECT Id, FirstName, LastName, Email FROM Contact WHERE AccountId = :acctId LIMIT 1];
        }
      
    }

    public PageReference insertContact() {
        Id acctId = this.AccountId;
        IF([SELECT Id, FirstName, LastName, Email FROM Contact WHERE AccountId = :acctId LIMIT 1].size()>0){ThisContact.Email = 'steelbrick_demo@salesforce.com';
            update ThisContact;
        }
        return ApexPages.currentPage();
        
    }

    public PageReference updateAccount() {
        update ThisAccount;
        return ApexPages.currentPage();
    }

    public PageReference CloseRedirect() {
        return this.Controller.view();
    }

    public PageReference resetAccountQuickQuote() {
        resetAccount();
        return Q2CGenerateQuickQuote.genQuote();
    }
    /**public PageReference resetAccountQuickInvoice() {
        resetAccount();
        return Q2CGenerateQuickInvoice.genQuote();
    }
    **/
    public PageReference resetAccountMasterQuote() {
        Id a = this.AccountId;
        Id quotetocopy = settings.Master_Quote__c;
        String AcctName = [SELECT Name FROM Account WHERE Id = :a].Name;
        resetAccount();
        Opportunity NewOpp = new Opportunity(Name = 'New Opportunity for ' + AcctName, CloseDate = Date.today(), StageName = 'Qualification', AccountId = a);
        insert NewOpp;
        List<SBQQ__Quote__c> Myquote = new List <SBQQ__Quote__c>();
        SObjectType objToken = Schema.getGlobalDescribe().get('SBQQ__Quote__c');
        DescribeSObjectResult objDef = objToken.getDescribe();
        Map<String, SObjectField> fields = objDef.fields.getMap();
        List<String> fieldslist = new List<String>();
        for (String s : fields.keySet()) {
            fieldslist.add(s);
        }
        String qq = 'SELECT ' + String.join(fieldslist, ',') + ' FROM SBQQ__Quote__c WHERE Id=:quotetocopy';
        System.debug(qq);
        Myquote = Database.query(qq);
        SBQQ__Quote__c Quote = Myquote.get(0).clone(false, true); //set new quotes
        Quote.SBQQ__StartDate__c = NewOpp.CloseDate.addDays(1);
        Quote.SBQQ__Opportunity2__c = NewOpp.Id;
        Quote.SBQQ__Account__c = NewOpp.Account.Id;
        Quote.SBQQ__Primary__c = true;
        insert Quote;

        List<SBQQ__QuoteLine__c> QLtoCopy = new List<SBQQ__QuoteLine__c>();

        SObjectType objToken1 = Schema.getGlobalDescribe().get('SBQQ__QuoteLine__c');
        DescribeSObjectResult objDef1 = objToken1.getDescribe();
        Map<String, SObjectField> fields1 = objDef1.fields.getMap();
        List<String> fieldslist1 = new List<String>();
        for (String s1 : fields1.keySet()) {
            fieldslist1.add(s1);
        }
        String q = 'SELECT ' + String.join(fieldslist1, ',') + ' FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c=:quotetocopy';
        System.debug(q);
        QLtoCopy = Database.query(q);


        List<SBQQ__QuoteLine__c> newQuoteLines = new List<SBQQ__QuoteLine__c>();
        
        Id newQuoteId=Quote.Id;
        SBQQ.TriggerControl.disable();
        for (Integer j = 0; j < QLtoCopy.size(); j++) { //through each quoteline (j)
            SBQQ__QuoteLine__c QuoteLine = QLtoCopy.get(j).clone(false, true);
            if (QLtoCopy.get(j).SBQQ__RequiredBy__c != null) {
                Id parent = QLtoCopy.get(j).SBQQ__RequiredBy__c;
                Decimal qlnumber = [SELECT SBQQ__Number__c FROM SBQQ__QuoteLine__c WHERE Id = :parent].SBQQ__Number__c;
                QuoteLine.SBQQ__RequiredBy__c = [SELECT Id FROM SBQQ__QuoteLine__c WHERE SBQQ__Number__c = :qlnumber AND SBQQ__Quote__c = :newQuoteId].Id;
            }
            QuoteLine.SBQQ__Group__c = null;
            QuoteLine.SBQQ__Quote__c = Quote.Id;

            insert QuoteLine;
            newQuoteLines.add(QuoteLine);
            
        }
        SBQQ.TriggerControl.enable();
        //insert newQuoteLines;

        return this.Controller.view();
    }
    //public PageReference quickInvoice() {
    //    resetAccount();
    //    return Q2CGenerateQuickInvoice.genQuote();
    //
    //}


    public PageReference resetAccountNewOpp() {
        Id a = this.AccountId;
        String AcctName = [SELECT Name FROM Account WHERE Id = :a].Name;
        resetAccount();
        Opportunity NewOpp = new Opportunity(Name = 'New Opportunity for ' + AcctName, CloseDate = Date.today(), StageName = 'Qualification', AccountId = a);
        insert NewOpp;
        return this.Controller.view();
    }

    public PageReference resetAccount() {
        updateCustomSettings();
        this.deleteDiscScheds();
        this.deleteQuotes();
        this.deleteOpportunities();
        this.deleteAssets();
        this.deleteSubscriptions();
        this.deleteContracts();
        this.deleteOrders();
        this.deleteContractedPrices();
        //this.deleteOrderConsumption();

        System.debug('Total Number of SOQL Queries in this apex code context: ' + Limits.getQueries());

        return this.Controller.view();
    }

    private Boolean updateCustomSettings() {
        try {
            update settings;

        } catch (Exception e) {
            return false;
        }
        return true;
    }


   

    private Boolean deleteDiscScheds() {
        Id a = this.AccountId;
        SBQQ__DiscountSchedule__c[] dsToDelete = [SELECT Id FROM SBQQ__DiscountSchedule__c WHERE SBQQ__Account__c = :a];
        if (!dsToDelete.isEmpty()) {
            Database.delete(dsToDelete);
        }

        System.debug('Total Number of SOQL Queries after deleteDiscScheds(): ' + Limits.getQueries());

        return true;
    }

    private Boolean deleteProcessInputValues(Set<Id> quotes) {
        Id a = this.AccountId;
        SBQQ__ProcessInputValue__c[] valuesToDelete = [SELECT Id FROM SBQQ__ProcessInputValue__c WHERE SBQQ__QuoteId__c IN :quotes];
        if (!valuesToDelete.isEmpty()) {
            Database.delete(valuesToDelete);
        }

        System.debug('Total Number of SOQL Queries after deleteProcessInputValues(): ' + Limits.getQueries());

        return true;
    }


  
    private Boolean deleteOrders() {
        Id a = this.AccountId;
        Order[] ordersToDelete = [SELECT Id FROM Order WHERE AccountId = :a];
        if (!ordersToDelete.isEmpty()) {
            Set<Id> orderIds = new Set<Id>();
            for (Order o : ordersToDelete) {
                orderIds.add(o.Id);
                //o.Status = 'Draft';
                //o.SBQQ__Contracted__c = false;
            }
            update ordersToDelete;
            OrderItem[] orderItems = getOrderItems(orderIds);
            if (!orderItems.isEmpty()) {
                for (OrderItem oi : orderItems) {
                    oi.SBQQ__Contracted__c = false;
                    oi.SBQQ__Status__c = 'Draft';
                    oi.SBQQ__Activated__c = false;
                    
                    System.debug(oi.OrderItemNumber + ' - ' + oi);
                }

                Database.update(orderItems);
                
            }
            for (Order o : ordersToDelete) {
                //orderIds.add(o.Id);
                o.Status = 'Draft';
                o.SBQQ__Contracted__c = false;
                System.debug(o.Name + ' - ' + o);
            }
            Database.update(ordersToDelete);
            Database.delete(ordersToDelete);
        }

        System.debug('Total Number of SOQL Queries after deleteOrders(): ' + Limits.getQueries());

        return true;
    }



   

    private Boolean deleteOpportunities() {
        Id a = this.AccountId;
        Opportunity[] opportinitiesToDelete = [SELECT Id FROM Opportunity WHERE AccountId = :a];
        if (!opportinitiesToDelete.isEmpty()) {
            Database.delete(opportinitiesToDelete);
        }

        System.debug('Total Number of SOQL Queries after deleteOpportunities(): ' + Limits.getQueries());

        return true;
    }

    private Boolean deleteAssets() {
        Id a = this.AccountId;
        Asset[] assetsToDelete = [SELECT Id FROM Asset WHERE AccountId = :a];
        if (!assetsToDelete.isEmpty()) {
            Database.delete(assetsToDelete);
        }

        System.debug('Total Number of SOQL Queries after deleteAssets(): ' + Limits.getQueries());

        return true;
    }

    private Boolean deleteSubscriptions() {
        Id a = this.AccountId;
        SBQQ__Subscription__c[] subscriptionsToDelete = [SELECT Id FROM SBQQ__Subscription__c WHERE SBQQ__Account__r.Id = :a];
        if (!subscriptionsToDelete.isEmpty()) {
            Database.delete(subscriptionsToDelete);
        }

        System.debug('Total Number of SOQL Queries after deleteSubscriptions(): ' + Limits.getQueries());

        return true;
    }

    private Boolean deleteContracts() {
        Id a = this.AccountId;
        Contract[] contractsToDelete = [SELECT Id, SBQQ__RenewalOpportunity__c FROM Contract WHERE AccountId = :a];
        if (!contractsToDelete.isEmpty()) {
            for (Contract c : contractsToDelete) {
                c.SBQQ__RenewalOpportunity__c = null;
            }
            Database.update(contractsToDelete);
            Database.delete(contractsToDelete);
        }

        System.debug('Total Number of SOQL Queries after deleteContracts(): ' + Limits.getQueries());

        return true;
    }

    private Boolean deleteQuotes() {
        Id a = this.AccountId;
        SBQQ__Quote__c[] quotesToDelete = [SELECT Id FROM SBQQ__Quote__c WHERE SBQQ__Account__r.Id = :a];
        if (!quotesToDelete.isEmpty()) {
            Set<Id> quoteIds = new Set<Id>();
            for (SBQQ__Quote__c q : quotesToDelete) {
                quoteIds.add(q.Id);
            }
            this.deleteProcessInputValues(quoteIds);
            Database.delete(quotesToDelete);
        }

        System.debug('Total Number of SOQL Queries after deleteQuotes(): ' + Limits.getQueries());

        return true;
    }



    private static List<OrderItem> getOrderItems(Set<Id> orderIds) {
        OrderItem[] orderItems = [SELECT Id FROM OrderItem WHERE OrderId IN :orderIds];
        return orderItems;
    }

   

    private Boolean deleteContractedPrices() {
        Id a = this.AccountId;
        if (settings.Delete_Contracted_Prices__c == true) {
            SBQQ__ContractedPrice__c[] cpToDelete = [SELECT Id FROM SBQQ__ContractedPrice__c WHERE SBQQ__Account__c = :a];
            if (!cpToDelete.isEmpty()) {
                Database.delete(cpToDelete);
            }
        }
        System.debug('Total Number of SOQL Queries after deletePaymentTransactions(): ' + Limits.getQueries());

        return true;
    }
   /** private Boolean deleteOrderConsumption() {
        Id a = this.AccountId;
        if (settings.Delete_Contracted_Prices__c == true) {
            SBQQ__OrderItemConsumptionSchedule__c[] ocToDelete = [SELECT Id FROM SBQQ__OrderItemConsumptionSchedule__c WHERE SBQQ__OrderItem__r.Order.AccountId = :a];
            if (!ocToDelete.isEmpty()) {
                Database.delete(ocToDelete);
            }
        }
        System.debug('Total Number of SOQL Queries after deletePaymentTransactions(): ' + Limits.getQueries());

        return true;
    }**/
   
}