objects/Asset.object
<CustomObject>
    <recordTypes>
        <fullName>Asset</fullName>
        <active>true</active>
        <description>For all standard Assets.</description>
        <label>Asset</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>CC Products</relationshipLabel>
        <relationshipName>CC_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CloudCrazeRedirectCntr.cls
public class CloudCrazeRedirectCntr {
    @AuraEnabled
    public Static List<String> commurl(String Community) {
        Network myCommunity = [SELECT Id FROM Network WHERE Name = :Community];
		ConnectApi.Community comm = ConnectApi.Communities.getCommunity(myCommunity.Id);
		List<String> BaseURL = comm.siteUrl.split('[/]');
        return BaseURL;
    }
    
    @AuraEnabled
    public static String BuildAssetOrderPartsLink(String Community,String Store, String AssetId){
        String url = '';
        Network myCommunity = [SELECT Id FROM Network WHERE Name = 'Professional Community'];
		ConnectApi.Community comm = ConnectApi.Communities.getCommunity(myCommunity.Id);
		List<String> BaseURL = comm.siteUrl.split('[/]');
        String AssetName = [SELECT Name FROM Asset WHERE Id = :AssetId].Name;
        String pid = [SELECT Product2Id from Asset WHERE Id = :AssetId].Product2Id ; 
        
        
        if(AssetName.Contains('Skid')){
            url = 'https://' + BaseURL[2] + '/DefaultStore/ccrz__ProductDetails?viewState=DetailView&cartID=&sku=93-00934';
        }else{
            /*String sku = [SELECT ccrz__SKU__c,Product__c from ccrz__E_Product__c WHERE Product__c = :pid].ccrz__SKU__c; 
        	/*url = 'https://' + BaseURL[2] + '/' + Store + '/ccrz__ProductDetails?viewState=DetailView&sku=' + sku; */
        	/*url = 'https://' + BaseURL[2] + '/' + Store + '/ccrz__ProductDetails?viewState=DetailView&sku=' + sku; */
            url = 'https://' + BaseURL[2] + '/' + Store + '/ccrz__Products?viewState=ListView'; 
            
        }
        return url; 
    }
	
}