objects/Asset.object
<CustomObject>
    <fields>
        <fullName>MFG_Partner_Central_Community_URL__c</fullName>
        <description>Used for Demo Configurator and SMS templates</description>
        <label>Partner Central Community URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MFG_Professional_Community_URL__c</fullName>
        <description>Used in Demo Configurator to hold Community URL.</description>
        <label>Professional Community URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Asset</fullName>
        <active>true</active>
        <description>For all standard Assets.</description>
        <label>Asset</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>ccrz__ActiveCart__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When a new Cart is created, the cart is active by default. Whenever, we want to make anyother cart active, the current active cart should be deactivated</description>
        <label>Active Cart</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__CartStatus__c</fullName>
        <description>Cart Status: Every cart is created with a &quot;Open&quot; state, and set to &quot;Closed&quot; state after a corresponding order is placed.</description>
        <label>Cart Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DemoSettings__c.object
<CustomObject>
    <description>Used by the Demo Configurator Tool built by Jesse Chase</description>
    <fields>
        <fullName>AllowEnable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AllowEnable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Completed_Description__c</fullName>
        <label>Completed Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Configuration_Name__c</fullName>
        <label>Configuration Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeveloperName__c</fullName>
        <formula>SUBSTITUTE( Name, &quot; &quot;, &quot;_&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DeveloperName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enablement_Description__c</fullName>
        <label>Enablement Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Demo Settings</label>
    <nameField>
        <label>Demo Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MFG_Recommended_Part__c.object
<CustomObject>
    <fields>
        <fullName>MFG_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipName>MFG_Recommended_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MFG_Commerce_Link__c</fullName>
        <label>Commerce Link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MFG_PartName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Name</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Recommended Parts</relationshipLabel>
        <relationshipName>Recommended_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recommended Part</label>
    <nameField>
        <label>Recommended Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommended Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DemoConfigurator.cls
global class DemoConfigurator{
    /** Get All Demo Settings from Demo Settings Object **/
	@AuraEnabled
    global static List<DemoSettings__c> GetSettings() {
        return [SELECT Id, Name,Completed_Description__c ,DeveloperName__c ,Configuration_Name__c,Enablement_Description__c,Enabled__c FROM DemoSettings__c WHERE AllowEnable__c = true Order By Order__c ASC];
    }
    /** Update Demo Settings to Enabled **/ 
	@AuraEnabled
    global static List<DemoSettings__c> UpdateDemoSetting(String WhichSetting) { 
        DemoSettings__c[] demosetting = [SELECT Id FROM DemoSettings__c WHERE DeveloperName__c = :WhichSetting]; 
            for(DemoSettings__c ds: demosetting) {
                ds.Enabled__c = true;
            }
        /** Attempt to update the demo setting fields and throw error in debug log if it fails **/
        try{
        	update demosetting;
            return [SELECT Id, Name,Completed_Description__c ,DeveloperName__c ,Configuration_Name__c,Enablement_Description__c,Enabled__c FROM DemoSettings__c WHERE AllowEnable__c = true Order By Order__c ASC];
        }catch(exception e){
            System.debug('Update Demo Setting Error: ' + e);
            return null;
        }
    }
    
    /** Get Org Base URL **/
    @AuraEnabled
    public static String getBaseURL(){
        return URL.getSalesforceBaseUrl().toExternalForm(); 
    } 
    @AuraEnabled
    public static List <String> getselectOptions(sObject objObject, string fld) {
      system.debug('objObject --->' + objObject);
      system.debug('fld --->' + fld);
      List < String > allOpts = new list < String > ();
      // Get the object type of the SObject.
      Schema.sObjectType objType = objObject.getSObjectType();
     
      // Describe the SObject using its object type.
      Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
     
      // Get a map of fields for the SObject
      map < String, Schema.SObjectField > fieldMap = objDescribe.fields.getMap();
     
      // Get the list of picklist values for this field.
      list < Schema.PicklistEntry > values =
       fieldMap.get(fld).getDescribe().getPickListValues();
     
      // Add these values to the selectoption list.
      for (Schema.PicklistEntry a: values) {
       allOpts.add(a.getValue());
      }
      system.debug('allOpts ---->' + allOpts);
      allOpts.sort();
      return allOpts;
     }
    /** Send Feedback to Demo Content Owner Via Email **/
    @AuraEnabled 
    public static void emailContentFeedback(String title, String reasonAttr, String unlineDescAttr,String email){
        Id userId = userInfo.getUserId();
        String OwnerEmail = email;
        String ContentTitle = title;
        String UserProfile = [SELECT ID FROM Profile WHERE Name = 'System Administrator'].Id;
        String UserEmail = [SELECT Email FROM User WHERE ProfileId = :UserProfile AND (UserRole.Name = 'CEO') LIMIT 1].Email;
        /* org information */
        String instanceName = [select InstanceName from Organization limit 1].InstanceName;
        Organization org = [SELECT id, Name, PrimaryContact  FROM Organization];
        Id orgId = org.Id;
        String Name = org.Name;
        String PrimContact = org.PrimaryContact;

        String EmailBody;
        String likedisliketext;
        EmailBody = '<h2>Content Feedback</h2>' +
                    '<strong>Demo Content</strong><br/>' +  ContentTitle + '<br/><br/>' + 
                    '<strong>Feedback Reason</strong><br/>' +  reasonAttr + '<br/><br/>' +
                    '<strong>Description</strong><br/>' +  unlineDescAttr + '<br/><br/><hr/>' + 
                    '<h2>Org Details</h2>' +
                    '<strong>Org Details</strong><br/>' +  instanceName + '<br/><br/>' + 
                    '<strong>Id: </strong>' +  orgId + ' | ' +
                    '<strong>Name: </strong>' +  Name + ' | ' +
                    '<strong>User: </strong> ' + PrimContact + ' | ' +  
                    '<strong>Email: </strong>' + UserEmail;
        
        String EmailSubj = 'Demo Content Feedback | ' + ContentTitle;
        
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.toAddresses = new String[] { OwnerEmail};
        message.optOutPolicy = 'FILTER';
        message.subject = EmailSubj;
        message.htmlBody = EmailBody;
        Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
        Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        
        if (results[0].success) {
            System.debug('The email was sent successfully.');
        } else {
            System.debug('The email failed to send: ' + results[0].errors[0].message);
        }
    }
    
    @AuraEnabled
    public static void RunRequiredSetup(){
        Network myCommunity = [SELECT Id FROM Network WHERE Name = 'Professional Community'];
		ConnectApi.Community comm = ConnectApi.Communities.getCommunity(myCommunity.Id);
		List<String> BaseURL = comm.siteUrl.split('[/]');
        /*Store URL : https://sdodemo-main-166ce2cf6b6-1698177dece.force.com/DefaultStore/ccrz__ProductDetails?sku=WTIN-ASMBLY*/
        
        MFG_Recommended_Part__c[] recparts = [SELECT Id, Name,MFG_PartName__r.ccrz__SKU__c ,MFG_Asset__c from MFG_Recommended_Part__c]; 
        for (MFG_Recommended_Part__c p : recparts) {
            p.MFG_Commerce_Link__c  = 'https://' + BaseURL[2] + '/DefaultStore/ccrz__ProductDetails?sku=' + p.MFG_PartName__r.ccrz__SKU__c ;
        }
        try{
        	update recparts;
        }catch(exception e){
            System.debug('Update Recommended Parts Object Error: ' + e);
        }
    }
    
    @AuraEnabled
    public static void BuildAssetURL(){
        Network myCommunity = [SELECT Id FROM Network WHERE Name = 'Professional Community'];
		ConnectApi.Community comm = ConnectApi.Communities.getCommunity(myCommunity.Id);
		List<String> BaseURL = comm.siteUrl.split('[/]');
        /*Store URL : https://sdodemo-main-166ce2cf6b6-1698177dece.force.com/DefaultStore/ccrz__ProductDetails?sku=WTIN-ASMBLY*/
        
        Asset[] assets = [SELECT Id from Asset]; 
        for (Asset a : assets) {
            a.MFG_Professional_Community_URL__c = 'https://' + BaseURL[2] + '/professional/';
            a.MFG_Partner_Central_Community_URL__c = 'https://' + BaseURL[2] + '/partnercentral/'; 
        }
        try{
        	update assets;
        }catch(exception e){
            System.debug('Update Recommended Parts Object Error: ' + e);
        }
    }
    
    @AuraEnabled
    public static void B2BSetup(){
    	/**
    	 * Updates all of the indexes 
		 */
        
        CkzUpdateCacheService.doUpdate();
        
        /**
         * Delete All Cloudcraze Carts
         */
        
        /*delete  [SELECT Id, ccrz__CartStatus__c, ccrz__ActiveCart__c FROM ccrz__E_Cart__c WHERE ccrz__ActiveCart__c = true AND ccrz__CartStatus__c = 'Open'];*/
    }
    
    @RemoteAction
    global static Map<String,Object> DataConnectors() {
        string sessionId = UserInfo.getSessionId();
        string base = URL.getSalesforceBaseUrl().toExternalForm();
        String url = base + '/services/data/v47.0/wave/dataConnectors';  
        
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setMethod('GET');
        
        String authorizationHeader = 'OAuth ' + sessionId;
        req.setHeader('Authorization', authorizationHeader);
        req.setHeader('Content-Type', 'application/json');
        
        // Send the request, and return a response
        HttpResponse res = h.send(req);
        
        Map<String,Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
        
        return responseMap;
        
    }
    /** Run all Analytics Dataflows with this handy snippet **/
    @RemoteAction
    global static void RunDataConnector(String ConnectorId) {
        string sessionId = UserInfo.getSessionId();
        string base = URL.getSalesforceBaseUrl().toExternalForm();
        string ingest = '/services/data/v47.0/wave/dataConnectors/' + ConnectorId + '/ingest';
        String url = base + ingest;  
        
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setMethod('POST');
        
        String authorizationHeader = 'OAuth ' + sessionId;
        req.setHeader('Authorization', authorizationHeader);
        req.setHeader('Content-Type', 'application/json');
        
        // Send the request, and return a response
        HttpResponse res = h.send(req);
        
    } 
    
}