objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Asset_Status__c</fullName>
        <label>Asset Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Service Needed</fullName>
                </value>
                <value>
                    <fullName>Service Needed</fullName>
                </value>
                <value>
                    <fullName>Outage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Coordinates__c</fullName>
        <defaultValue>&quot;43.4023268,-88.489216&quot;</defaultValue>
        <description>https://www.google.com/maps/@43.4023268,-88.489216,316m/data=!3m1!1e3</description>
        <label>Coordinates</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entitlement_Status__c</fullName>
        <label>Warranty Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>30 Day Warning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MFG_BaseUrl__c</fullName>
        <formula>LEFT($Api.Partner_Server_URL_340, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_340))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MFG_BaseUrl</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MFG_IDO_IOT_Status__c</fullName>
        <label>IOT Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Normal</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Map__c</fullName>
        <defaultValue>&quot;https://www.google.com/maps/@43.4023268,-88.489216,316m/data=!3m1!1e3&quot;</defaultValue>
        <label>Map</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Status_Indicator_URL_Public__c</fullName>
        <formula>CASE(TEXT(MFG_IDO_IOT_Status__c), 
&quot;Normal&quot;, 
&quot;https://mfg-ido.s3.us-east-2.amazonaws.com/Images/Miscellaneous+IDO+Images/Icon+-+Good.png&quot;, 

&quot;Error&quot;,
&quot;https://mfg-ido.s3.us-east-2.amazonaws.com/Images/Miscellaneous+IDO+Images/Icon-+General+Bad.png&quot;, 
 
&quot;https://mfg-ido.s3.us-east-2.amazonaws.com/Images/Miscellaneous+IDO+Images/Icon-+General+Warning.png&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status Indicator URL Public</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warranty_Indicator__c</fullName>
        <formula>IMAGE(URLsrc__c&amp;&quot;/servlet/servlet.ImageServer?id=&quot;&amp;CASE( Entitlement_Status__c, 
&quot;Expired&quot;, &quot;015Hr000003iK9b&amp;oid=00DHr0000010MFf&quot;, 
&quot;Active&quot;,&quot;015Hr000003iK9Z&amp;oid=00DHr0000010MFf&quot;, 
&quot;30 Day Warning&quot;, &quot;015Hr000003iK9a&amp;oid=00DHr0000010MFf&quot;, 
&quot;015Hr000003iK9Z&amp;oid=00DHr0000010MFf&quot;),&quot;Active Contract?&quot;,24,24)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Warranty</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WarranyIndPublic__c</fullName>
        <formula>CASE( Entitlement_Status__c, 

&quot;Expired&quot;, &quot;https://mfg-ido.s3.us-east-2.amazonaws.com/Images/Miscellaneous+IDO+Images/Icon-+General+Bad.png&quot;, 

&quot;Active&quot;,&quot;https://mfg-ido.s3.us-east-2.amazonaws.com/Images/Miscellaneous+IDO+Images/Icon+-+Good.png&quot;, 

&quot;30 Day Warning&quot;, &quot;https://mfg-ido.s3.us-east-2.amazonaws.com/Images/Miscellaneous+IDO+Images/Icon-+General+Warning.png&quot;,

&quot;https://mfg-ido.s3.us-east-2.amazonaws.com/Images/Miscellaneous+IDO+Images/Icon-+General+Bad.png&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>WarranyIndPublic</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Asset</fullName>
        <active>true</active>
        <description>For all standard Assets.</description>
        <label>Asset</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Case</fullName>
        <active>true</active>
        <businessProcess>Standard Support Process</businessProcess>
        <description>Primary case record type used for most cases.</description>
        <label>Case</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Image_URL__c</fullName>
        <label>Image URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MFG_Image_URL__c</fullName>
        <description>Used by to reference Product Images on AWS. Referenced for Asset Components in the Community and PURL field</description>
        <label>MFG_Image_URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>purl__c</fullName>
        <formula>IF( MFG_Image_URL__c != null, MFG_Image_URL__c, &apos;https://s3.amazonaws.com/rcgidoimages/CG/noImage.png&apos;)</formula>
        <label>purl</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Turbine_Metrics__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Asset Metrics</relationshipLabel>
        <relationshipName>Asset_Metrics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Avg_kW_Output__c</fullName>
        <label>Evaporator Flow (gpm)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_Time_Reported__c</fullName>
        <label>Date/Time Reported</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Direction__c</fullName>
        <label>Condenser Flow (gpm)</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours This Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lifetime_Hours__c</fullName>
        <label>Lifetime Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Operational_Status_URL__c</fullName>
        <formula>IF( TEXT(Operational_Status__c) = &quot;Online Active&quot;, 
(&quot;https://carriernext--c.documentforce.com/servlet/servlet.ImageServer?id=015Hr000003iK9W&amp;oid=00DHr000001CWQf&amp;lastMod=1552667189000&quot;), 

IF ( TEXT(Operational_Status__c) = &quot;Offline&quot;, 
(&quot;https://carriernext--c.documentforce.com/servlet/servlet.ImageServer?id=015Hr000003iK9V&amp;oid=00DHr000001CWQf&amp;lastMod=1552667210000&quot;), 

IF ( TEXT(Operational_Status__c) = &quot;Online Idle&quot;,(&quot;https://carriernext--c.documentforce.com/servlet/servlet.ImageServer?id=015Hr000003iK9X&amp;oid=00DHr000001CWQf&amp;lastMod=1552667238000&quot;), 
(&quot;https://carriernext--c.documentforce.com/servlet/servlet.ImageServer?id=015Hr000003iK9V&amp;oid=00DHr000001CWQf&amp;lastMod=1552667210000&quot;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Operational Status URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operational_Status__c</fullName>
        <label>Operational Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Offline</fullName>
                </value>
                <value>
                    <fullName>Online Active</fullName>
                </value>
                <value>
                    <fullName>Online Idle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RPM__c</fullName>
        <label>SEER</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>kW_Indicator_URL__c</fullName>
        <formula>IF( kW_Output_Current__c &lt; 500,(&quot;https://gerenew--c.documentforce.com/servlet/servlet.ImageServer?id=015Hr000003iK9S&amp;oid=00DHr000001CWQe&amp;lastMod=1551197461000&quot;), 
IF ( kW_Output_Current__c &lt; 2000,(&quot;https://gerenew--c.documentforce.com/servlet/servlet.ImageServer?id=015Hr000003iK9T&amp;oid=00DHr000001CWQe&amp;lastMod=1551197621000&quot;), 
IF ( kW_Output_Current__c &gt; 2001,(&quot;https://gerenew--c.documentforce.com/servlet/servlet.ImageServer?id=015Hr000003iK9U&amp;oid=00DHr000001CWQe&amp;lastMod=1551197648000&quot;), (&quot;https://gerenew--c.documentforce.com/servlet/servlet.ImageServer?id=015Hr000003iK9S&amp;oid=00DHr000001CWQe&amp;lastMod=1551197461000&quot;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>kW Indicator URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>kW_Indicator__c</fullName>
        <formula>IF( kW_Output_Current__c &lt; 500, IMAGE(&quot;https://gerenew--c.documentforce.com/servlet/servlet.ImageServer?id=015Hr000003iK9S&amp;oid=00DHr000001CWQe&amp;lastMod=1551197461000&quot;, &quot;Red&quot;,100,100), 
IF ( kW_Output_Current__c &lt; 2000, IMAGE(&quot;https://gerenew--c.documentforce.com/servlet/servlet.ImageServer?id=015Hr000003iK9T&amp;oid=00DHr000001CWQe&amp;lastMod=1551197621000&quot;, &quot;Yellow&quot;,100,100), 
IF ( kW_Output_Current__c &gt; 2001, IMAGE(&quot;https://gerenew--c.documentforce.com/servlet/servlet.ImageServer?id=015Hr000003iK9U&amp;oid=00DHr000001CWQe&amp;lastMod=1551197648000&quot;, &quot;Green&quot;,100,100), 
IMAGE(&quot;https://gerenew--c.documentforce.com/servlet/servlet.ImageServer?id=015Hr000003iK9S&amp;oid=00DHr000001CWQe&amp;lastMod=1551197461000&quot;, &quot;Red&quot;,100,100))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Output Indicator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>kW_Output_Current__c</fullName>
        <label>EER</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>kW_Output_Daily_High__c</fullName>
        <label>kW Output (Daily High)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>kW_Output_Daily_Low__c</fullName>
        <label>kW Output (Daily Low)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>kW_Output_Monthly_Avg__c</fullName>
        <label>AVG Energy Draw (amps)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Asset Metric</label>
    <nameField>
        <displayFormat>AM-{0000000}</displayFormat>
        <label>Asset Metric ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LightningAssetsControllerRecId.cls
public class LightningAssetsControllerRecId {
      
@AuraEnabled
public static String getBaseUrl () {
    if (Network.getNetworkId() != null) {
        return [SELECT Id, UrlPathPrefix FROM Network WHERE Id = :Network.getNetworkId()].UrlPathPrefix;
    }
    return '';
}

    
@AuraEnabled
public static String getUIThemeDescription() {
    return UserInfo.getUiThemeDisplayed();
}
  /*
   //Dan Shannon commented; if Asset Info is needed on the WorkOrder record
   
    @AuraEnabled
    public static List<Asset> getAssetDetailWO(String recordId){
    
        system.debug('WO RecId: ' + recordId);
        
            List<WorkOrder> woList = [SELECT Asset.Id FROM WorkOrder WHERE Id =: recordId];
            system.debug('wo RecId: ' + woList.Size());   
            for(WorkOrder w : woList){
            
                system.debug('return AssetId: ' + w.Asset.Id);  
                return [Select Id, Map__c,Coordinates__c,Location.Id,Location.Name, Asset_Status__c ,Product2.Name,WarranyIndPublic__c,Status_Indicator_URL_Public__c , Warranty_Ind_URL_Public__c , AccountId,Community_Image_URL__c,SerialNumber,Name, Entitlement_Status__c, Operational_Status_Ind_URL__c, Operational_Status__c 
                   From Asset
                   Where id =: w.Asset.Id

                 ];
        }
        system.debug('return null');
        return null;

      }  
    
    */
    
    /*
     //Dan Shannon commented; if Asset Info is needed on the Oppty record
    @AuraEnabled
    public static List<Asset> getAssetDetailOppty(String recordId){
    
        system.debug('WO RecId: ' + recordId);
        
            List<Opportunity> opptyList = [SELECT Asset__r.Id FROM Opportunity WHERE Id =: recordId];
            system.debug('oppty RecId: ' + opptyList.Size());   
            for(Opportunity o : opptyList){
            
                system.debug('return AssetId: ' + o.Asset__r.Id);  
                return [Select Id, Map__c,Coordinates__c,Location.Id,Location.Name, Asset_Status__c ,Product2.Name,WarranyIndPublic__c,Status_Indicator_URL_Public__c , Warranty_Ind_URL_Public__c , AccountId,Community_Image_URL__c,SerialNumber,Name, Entitlement_Status__c, Operational_Status_Ind_URL__c, Operational_Status__c 
                   From Asset
                   Where id =: o.Asset__r.Id

                 ];
        }
        system.debug('return null');
        return null;

      }  
    
    */
    
    
    
    @AuraEnabled
    public static List<Turbine_Metrics__c > getAssetMetrics(String recordId){
    
        system.debug('Turbine_Metrics__c RecId: ' + recordId);
        
            List<Asset> assetList = [SELECT Asset.Id FROM Asset WHERE Id =: recordId];
            //system.debug('wo RecId: ' + woList.Size());   
            for(Asset a : assetList){
            
                //system.debug('return AssetId: ' + w.Asset.Id);  
                return [Select Id,Asset__r.LocationId, Operational_Status_URL__c, Asset__r.Name, kW_Indicator_URL__c ,Date_Time_Reported__c,Direction__c,Hours__c,kW_Indicator__c,kW_Output_Current__c,Avg_kW_Output__c,kW_Output_Daily_High__c,kW_Output_Daily_Low__c,kW_Output_Monthly_Avg__c,LastModifiedById,Lifetime_Hours__c,Operational_Status__c,OwnerId,RPM__c
                   From Turbine_Metrics__c 
                   Where Asset__r.Id =: a.Id
                   ORDER BY Date_Time_Reported__c DESC

                 ];
        }
        system.debug('return null');
        return null;

      }  


    @AuraEnabled
    public static List<Asset> getAsset(String recordId){
    
        system.debug('RecId: ' + recordId);
//        User loggedInUser=[Select Id, ContactId, Contact.AccountId From User Where Id =:UserInfo.getUserId() LIMIT 1];
                //orig: //return [Select Id, Map__c,Coordinates__c,Location.Id,Location.Name, Asset_Status__c ,Product2.Name,WarranyIndPublic__c,Status_Indicator_URL_Public__c , Warranty_Ind_URL_Public__c , AccountId,Community_Image_URL__c,SerialNumber,Name, Entitlement_Status__c, Operational_Status_Ind_URL__c, Operational_Status__c 
                return [Select Id,Product2.MFG_Image_URL__c ,MFG_BaseUrl__c ,Product2.Image_URL__c,Map__c,MFG_IDO_IOT_Status__c ,Location.Id,Location.Name, Asset_Status__c ,Product2.Name,WarranyIndPublic__c,Status_Indicator_URL_Public__c, AccountId, Product2.purl__c,SerialNumber,Name, Entitlement_Status__c
                        //, 
                        //Operational_Status_Ind_URL__c, 
                        //Operational_Status__c                         
                   From Asset
                   Where Asset.id =: recordId

                   //Limit 20 
                 ];
      }
    
    
                 @AuraEnabled
    public static List<Asset> getAssets(String recordId){
    
        	id userId = UserInfo.getUserId();
			User u = [select id, accountId, contactId from User where id = : userId];
			id getContactId = u.contactId;
            id acctId = u.accountId;
			system.debug('getContactId' + getContactId);
        
        system.debug('RecId: ' + recordId);
//        User loggedInUser=[Select Id, ContactId, Contact.AccountId From User Where Id =:UserInfo.getUserId() LIMIT 1];
        //orig: //return   [Select Id, Map__c,Coordinates__c,Location.Id,Location.Name, Asset_Status__c ,Product2.Name,WarranyIndPublic__c,Status_Indicator_URL_Public__c , Warranty_Ind_URL_Public__c , AccountId,Community_Image_URL__c,SerialNumber,Name, Entitlement_Status__c, Operational_Status_Ind_URL__c, Operational_Status__c 
        return   [Select Id,MFG_BaseUrl__c ,Product2.MFG_Image_URL__c ,Product2.Image_URL__c,Map__c,Location.Id,MFG_IDO_IOT_Status__c ,Location.Name, Asset_Status__c ,Product2.Name,WarranyIndPublic__c,Status_Indicator_URL_Public__c, AccountId,Product2.purl__c,SerialNumber,Name, Entitlement_Status__c
                  //, 
                  //Operational_Status_Ind_URL__c, 
                  //Operational_Status__c  
                   From Asset
                   //Where Account.id =: recordId AND Asset_Status__c !=: ''
                   Where Account.id =: acctId AND Asset_Status__c != ''
                   ORDER BY SerialNumber ASC
                   //Limit 20 
                 ];
      }
    
 
    @AuraEnabled
    public static List<Asset> getAssetDetail(String recordId){
    
        system.debug('case RecId: ' + recordId);
        
            List<Case> caseList = [SELECT Asset.Id FROM Case WHERE Id =: recordId];
                  system.debug('case RecId: ' + caseList.Size());   
        for(Case c : caseList){
            
                system.debug('return AssetId: ' + c.Asset.Id);  
//orig://                return [Select Id, Map__c,Coordinates__c,Asset_Status__c ,Product2.Name,WarranyIndPublic__c,Status_Indicator_URL_Public__c , Warranty_Ind_URL_Public__c , AccountId,Community_Image_URL__c,SerialNumber,Name, Entitlement_Status__c
                return [Select Id,MFG_BaseUrl__c ,Product2.MFG_Image_URL__c ,Product2.Image_URL__c,Map__c,MFG_IDO_IOT_Status__c ,Asset_Status__c ,Product2.Name,WarranyIndPublic__c,Status_Indicator_URL_Public__c, AccountId,Product2.purl__c,SerialNumber,Name, Entitlement_Status__c                        
                   From Asset
                   Where id =: c.Asset.Id 

                 ];
        }
        system.debug('return null');
        return null;

      }
    
    /*
      @AuraEnabled
    public static List<Asset> getAssets(String recordId){
    

        
//        User loggedInUser=[Select Id, ContactId, Contact.AccountId From User Where Id =:UserInfo.getUserId() LIMIT 1];
        return   [Select Id, Name,Status1__c,Status2__c,Status3__c,Status1_Ind__c,Status2_Ind__c,Status3_Ind__c
                  From Asset
                   Where Account.id =: recordId
                  ORDER BY Status1__c ASC
                   Limit 10 ];
      }
    
             @AuraEnabled
    public static List<Asset> getAssetsAccount(String recordId){
    

//        User loggedInUser=[Select Id, ContactId, Contact.AccountId From User Where Id =:UserInfo.getUserId() LIMIT 1];
        return   [Select Id, AccountId, ListImage_URL__c, Tail_Number__c,SerialNumber ,Name,Status1__c,Status2__c,Status3__c,Status1_Ind__c,Status2_Ind__c,Status3_Ind__c,Entitlement_Status__c 
                   From Asset
                   Where Account.id =: recordId AND Tail_Number__c !=: ''
                  ORDER BY Tail_Number__c ASC
                   //Limit 20 
                 ];
      }
*/    
    /*
        @AuraEnabled
    public static List<A_C_Relationship__c> getACRelationship(String recordId){
    
         system.debug('getting relationships:' + recordId);
//        User loggedInUser=[Select Id, ContactId, Contact.AccountId From User Where Id =:UserInfo.getUserId() LIMIT 1];
        return   [Select Id, Aircraft__r.Product2.Name, Aircraft__r.ListImage_URL__c  ,  Aircraft_User__c, Aircraft_User__r.Name, Management_Co__c , Management_Co__r.Name,Owner__c,Owner__r.Name , Aircraft__c, Aircraft__r.Warranty_Ind_URL__c ,Aircraft__r.Warranty_Indicator__c,  Aircraft__r.Tail_Number__c,Aircraft__r.SerialNumber ,Aircraft__r.Name,Aircraft__r.Entitlement_Status__c 
                   From A_C_Relationship__c 
                   Where Owner__r.id =: recordId AND Aircraft__r.Tail_Number__c !=: ''
                  ORDER BY Aircraft__r.Tail_Number__c DESC
                   //Limit 20 
                 ];
      }    

            @AuraEnabled
    public static List<A_C_Relationship__c> getACRelationshipManagement(String recordId){
    
         system.debug('getting relationships:' + recordId);
//        User loggedInUser=[Select Id, ContactId, Contact.AccountId From User Where Id =:UserInfo.getUserId() LIMIT 1];
        return   [Select Id, Aircraft__r.Product2.Name, Aircraft__r.Product2.Community_Image_URL__c  ,  Aircraft_User__c, Aircraft_User__r.Name, Management_Co__c , Management_Co__r.Name,Owner__c,Owner__r.Name , Aircraft__c, Aircraft__r.Warranty_Ind_URL__c ,Aircraft__r.Warranty_Indicator__c,  Aircraft__r.Tail_Number__c,Aircraft__r.SerialNumber ,Aircraft__r.Name,Aircraft__r.Entitlement_Status__c 
                   From A_C_Relationship__c 
                   Where Management_Co__r.id =: recordId AND Aircraft__r.Tail_Number__c !=: ''
                  ORDER BY Aircraft__r.Tail_Number__c DESC
                   //Limit 20 
                 ];
      } 
*/
}