objects/Campaign_Message__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Message__c</fullName>
        <label>Campaign Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>Camping_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Conclusion__c</fullName>
        <label>Conclusion</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Introduction__c</fullName>
        <label>Introduction</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Campaign Message</label>
    <nameField>
        <displayFormat>CME-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CampaignPersonalizationCtrl.cls
public without sharing class CampaignPersonalizationCtrl {
	@AuraEnabled
    public static void savePersonalization(Id campaignId, String Introduction, String Conclusion) {
        Campaign_Message__c c = [SELECT Id, Introduction__c, Conclusion__c FROM Campaign_Message__c WHERE Campaign__c =: campaignId];
        c.Introduction__c = Introduction;
        c.Conclusion__c = Conclusion;
        
        try {
            upsert c;
        }
        catch(DMLException err) {
            System.debug('problem saving intro and conclusion--'+err);
        }
    }
}