objects/Campaign_Message__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Members__c</fullName>
        <label>Approved Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Campaign_Message__c</fullName>
        <label>Campaign Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>Camping_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rejected_Members__c</fullName>
        <label>Rejected Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Campaign Message</label>
    <nameField>
        <displayFormat>CME-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CampaignPendingApprovalsCtrl.cls
public without sharing class CampaignPendingApprovalsCtrl {
	@AuraEnabled
    public static List<PendingMembers> fetchCampaignMembers(Id campaignId) {
        List<PendingMembers> memberList = new List<PendingMembers>();
        
        //Getting all added leads and adding to member list
        List<CampaignMember> leadList = [SELECT Id, Name, Status, LeadId 
                                     	   FROM CampaignMember 
                                           WHERE CampaignId =: campaignId AND LeadId != null];
        for(CampaignMember l: leadList) {
           PendingMembers plead = new PendingMembers();
           plead.memberId = l.LeadId;
           plead.Name = l.Name;
           plead.Status = l.Status;
           memberList.add(plead);
        }
        
        //Getting all contacts and adding to member List
        List<CampaignMember> contactList = [SELECT Id, Name, Status, ContactId 
                                     	   FROM CampaignMember 
                                           WHERE CampaignId =: campaignId AND ContactId != null];
        for(CampaignMember c: contactList) {
           PendingMembers pcontact = new PendingMembers();
           pcontact.memberId = c.ContactId;
           pcontact.Name = c.Name;
           pcontact.Status = c.Status;
           memberList.add(pcontact);
        }
        
        return memberList;
    }
    
    //getting the number of approved members
    @AuraEnabled
    public static Campaign_Message__c saveApprovedMemberNo(Id campaignId, Integer appnum) {
        Campaign_Message__c c = [SELECT Id,Approved_Members__c FROM Campaign_Message__c WHERE Campaign__c =: campaignId];
        c.Approved_Members__c = Integer.valueOf(appnum);
        System.debug(c);
        try {
            update c;
        }
        catch(DMLException err){
            System.debug('Error Occured--'+err);
        }
        return c;
    }

    //getting the number of rejected members    
    @AuraEnabled
    public static Campaign_Message__c saveRejectedMemberNo(Id campaignId, Integer rejnum) {
        System.debug('rejnum');
        System.debug(rejnum);
        Campaign_Message__c c1 = [SELECT Id,Rejected_Members__c FROM Campaign_Message__c WHERE Campaign__c =: campaignId];
        c1.Rejected_Members__c = Integer.valueOf(rejnum);
        try {
            update c1;
        }
        catch(DMLException err){
            System.debug('Error Occured--'+err);
        }
        return c1;
    }
}