objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>Use_Quote_Overrides__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approve Quote Overrides</label>
        <type>Checkbox</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ccrz__E_CartItem__c.object
<CustomObject>
    <description>Cart Items</description>
    <fields>
        <fullName>QuotedPrice__c</fullName>
        <label>Quoted Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The unit price of the line.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Quantity of the line item.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SubAmount__c</fullName>
        <description>Sub Amount total for the line.  Typically will be Price times Quantity.</description>
        <label>Sub Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>quotedQty__c</fullName>
        <label>Quoted Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CC Cart Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CartItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ckzCPQLogicCartPrice.cls
global with sharing class ckzCPQLogicCartPrice extends ccrz.ccLogicCartPrice {
    
    global virtual override Map<String, Object> applyPricing(Map<String, Object> inputData) {

        ccrz.ccLog.log(LoggingLevel.DEBUG, 'ckzCPQLogicCartPrice', 'begin applyPricing');

        // invoke out-of-box pricing to prevent duplicating work
        super.applyPricing(inputData);

        ccrz__E_Cart__c cartObj = (ccrz__E_Cart__c)inputData.get('cartToPrice');
        List<ccrz__E_CartItem__c> cartItems = (List<ccrz__E_CartItem__c>) inputData.get('cartItemsToPrice');

        //ccrz.ccLog.log(LoggingLevel.DEBUG, 'ckzCPQLogicCartPrice', JSON.serialize(cartItems));
        ccrz.ccLog.log(LoggingLevel.DEBUG, 'ckzCPQLogicCartPrice', cartItems);

        ccrz.ccLog.log(LoggingLevel.DEBUG, 'ckzCPQLogicCartPrice', 'cartItems size = ' + cartItems.size());

        // Adjust items here
        if(cartObj.Use_Quote_Overrides__c){

            ccrz.ccLog.log(LoggingLevel.DEBUG, 'ckzCPQLogicCartPrice', 'use quote override in effect');

            Map<Id, ccrz__E_CartItem__c> cartItemObjMap = new Map<Id, ccrz__E_CartItem__c>();

            for(ccrz__E_CartItem__c cartItemObj : cartItems) {

                ccrz.ccLog.log(LoggingLevel.DEBUG, 'ckzCPQLogicCartPrice', 'quoted price: ' + cartItemObj.QuotedPrice__c);
                ccrz.ccLog.log(LoggingLevel.DEBUG, 'ckzCPQLogicCartPrice', 'quoted qty: ' + cartItemObj.quotedQty__c);

                if(cartItemObj.QuotedPrice__c != null) {

                    cartItemObj.ccrz__Price__c = cartItemObj.QuotedPrice__c;

                    if(cartItemObj.quotedQty__c != null) {
                        cartItemObj.ccrz__quantity__c = cartItemObj.quotedQty__c;
                    }

                    cartItemObj.ccrz__subAmount__c = cartItemObj.ccrz__price__c * cartItemObj.ccrz__quantity__c;

                    ccrz.ccLog.log(LoggingLevel.DEBUG, 'ckzCPQLogicCartPrice', 'new sub amount: ' + cartItemObj.ccrz__subAmount__c);
                }

                cartItemObjMap.put(cartItemObj.Id, cartItemObj);
            }
            
        }

        ccrz.ccLog.log(LoggingLevel.DEBUG, 'ckzCPQLogicCartPrice', 'exit applyPricing');
        return inputData;
    }

}