objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>CC Carts</relationshipLabel>
        <relationshipName>CC_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Account of the User that this cart was created for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>E_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Contact of the User that this cart was created for.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CC Carts</relationshipLabel>
        <relationshipName>CC_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ccrz__E_CartItem__c.object
<CustomObject>
    <description>Cart Items</description>
    <fields>
        <fullName>Quote_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>CC Cart Items</relationshipLabel>
        <relationshipName>CC_Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Cart__c</fullName>
        <description>Reference to the parent cart.</description>
        <label>Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>E_CartItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The unit price of the line.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line item.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Cart Items (ProductID)</relationshipLabel>
        <relationshipName>E_CartItem2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Quantity of the line item.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CC Cart Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CartItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>CC Products</relationshipLabel>
        <relationshipName>CC_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Ecommerce_Cart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ecommerce Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__PriceBook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Price Book associated with this Quote.</description>
        <inlineHelpText>Price Book associated with this Quote.</inlineHelpText>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__PricebookId__c</fullName>
        <description>ID of the Price Book used by this quote.</description>
        <inlineHelpText>ID of the Price Book used by this quote.</inlineHelpText>
        <label>Pricebook ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
        <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Ecommerce_Cart_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ecommerce Cart Item</label>
        <referenceTo>ccrz__E_CartItem__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Incomplete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag set internally by application logic when a line is saved to an incomplete database. This may happen when price rules are evaluated. Test this field in validation rules to avoid them firing prematurely. Do NOT add to page layout or otherwise update.</description>
        <inlineHelpText>Flag set internally by application logic when a line is saved to an incomplete database. This may happen when price rules are evaluated. Test this field in validation rules to avoid them firing prematurely. Do NOT add to page layout or otherwise update.</inlineHelpText>
        <label>Incomplete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__ListPrice__c</fullName>
        <description>List unit price for the product quoted by this line item. List Price originates from the price book.</description>
        <inlineHelpText>List unit price for the product quoted by this line item. List Price originates from the price book.</inlineHelpText>
        <label>List Unit Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__NetPrice__c</fullName>
        <description>Net unit price for the product quoted by this line item.</description>
        <inlineHelpText>Net unit price for the product quoted by this line item.</inlineHelpText>
        <label>Net Unit Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__SpecialPriceType__c</fullName>
        <description>Stores the type of special price offered on this line item. Null value indicates there is no special pricing. Under normal circumstances this field should not be modified via UI.</description>
        <inlineHelpText>Stores the type of special price offered on this line item. Null value indicates there is no special pricing.</inlineHelpText>
        <label>Special Price Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contracted Price</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__SpecialPrice__c</fullName>
        <description>Special (volume-discounted or contracted) unit price for the product being quoted by this line item.</description>
        <inlineHelpText>Special unit price for this line item, such as volume discount or contracted price.</inlineHelpText>
        <label>Special Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CloudCrazeCPQConnector.cls
public class CloudCrazeCPQConnector{
    public Id quoteId {get; set;}
    public Id cartId {get; set;}
    public Id scId {get; set;}
    Schema.sObjectType type {get; set;}
    public SBQQ__Quote__c quote {get; set;}
    public ccrz__E_Cart__c cart {get; set;}
    public List<ccrz__E_CartItem__c> cartItems {get; set;}
    public List<SBQQ__QuoteLine__c> quoteLines {get; set;}
    
    public CloudCrazeCPQConnector(ApexPages.StandardController sc){
        system.debug('In the controller');
        this.scId = sc.getId();
        system.debug('Id was set to ' + this.scId);
        this.type = sc.getRecord().getSObjectType();
        
    }

    public void processCart(Id id){
        system.debug('Process Cart Called');
        this.cartId = id;
        system.debug('Set the cart ID to ' + this.cartId);
        fetchCart();
    }

    public void fetchCart(){
        system.debug('Fetching Cart...');
        this.cart = [SELECT Id, Quote__c, ccrz__Account__c, ccrz__Contact__c FROM ccrz__E_Cart__c WHERE Id = :this.cartId];
        if(this.cart.Quote__c != NULL){
            system.debug('Cart Already Had a quote');
            this.quoteId = this.cart.Quote__c;
        }
        else{
            system.debug('Cart has no quote.');
            createQuoteFromCart();
        }
    }

    public void createQuoteFromCart(){
        system.debug('createQuoteFromCart Method Invoked');
        String P_Id = [Select Id,Name FROM Pricebook2 WHERE NAME = 'Standard Price Book'].Id;
        this.quote = new SBQQ__Quote__c(SBQQ__Account__c = this.cart.ccrz__Account__c, SBQQ__PrimaryContact__c = this.cart.ccrz__Contact__c, SBQQ__PriceBook__c = P_Id, SBQQ__PricebookId__c = P_Id, Ecommerce_Cart__c = this.cartId);
        try{
            system.debug('Trying to Insert Quote ');
            database.insert(this.quote);    
        }
        catch(Exception e){
            system.debug('Insert Failed...');
            system.debug(e.getMessage());
        }
        
        this.quoteId = this.quote.Id;
        this.cart.Quote__c = this.quote.Id;
        database.update(this.cart);

        createQuoteLinesFromCartLines();


    }

    public void createQuoteLinesFromCartLines(){
        system.debug('Starting to Create Quote Lines');
        this.cartItems = [SELECT Name, Id, ccrz__Product__r.Product__c, ccrz__Quantity__c, ccrz__Price__c, Quote_Line__c FROM ccrz__E_CartItem__c WHERE ccrz__Cart__c = :this.cartId and ccrz__Product__r.Product__c != null];
        this.quoteLines = new List<SBQQ__QuoteLine__c>();
        for(ccrz__E_CartItem__c cartItem : this.cartItems){
            system.debug('Found Cart Item ' + cartItem.Name);
            SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c();
            quoteLine.SBQQ__Product__c = cartItem.ccrz__Product__r.Product__c;
            quoteLine.SBQQ__Quantity__c = cartItem.ccrz__Quantity__c;
            quoteLine.SBQQ__SpecialPrice__c = cartItem.ccrz__Price__c;
            quoteLine.SBQQ__SpecialPriceType__c = 'Custom';
            quoteLine.SBQQ__Quote__c = this.quoteId;
            quoteLine.Ecommerce_Cart_Item__c = cartItem.Id;
            quoteLine.SBQQ__Incomplete__c = true;
            //NEW
            quoteLine.SBQQ__ListPrice__c = cartItem.ccrz__Price__c;
            quoteLine.SBQQ__NetPrice__c = cartItem.ccrz__Price__c;
            this.quoteLines.add(quoteLine);
        }
        database.insert(this.quoteLines);

        Map<Id, Id> cartItem2quoteLineMap = new Map<Id, Id>();

        for(SBQQ__QuoteLine__c quoteLine : this.quoteLines){
            cartItem2quoteLineMap.put(quoteLine.Ecommerce_Cart_Item__c, quoteLine.Id);
        }

        for(ccrz__E_CartItem__c cartItem : this.cartItems){
            cartItem.Quote_Line__c = cartItem2quoteLineMap.get(cartItem.Id);
        }

        database.update(this.cartItems);

    }

    public ApexPages.PageReference goToQuoteLineEditor(){
        system.debug('In the Redirect');
        if(this.type == Schema.ccrz__E_Cart__c.getSObjectType()){
            system.debug('The VF Controller Thinks this is a Cart');
            processCart(this.scId);
        }

        return new ApexPages.PageReference('/apex/SBQQ__sb?scontrolCaching=1&id=' + quoteId);
    }

    public static void syncQuoteLinesToCartItems(List<SBQQ__QuoteLine__c> lines){
        List<Id> quoteLineIds = new List<Id>();
        Map<Id, Decimal> quoteLine2priceMap = new Map<Id, Decimal>();
        Map<Id, Decimal> quoteLine2quantityMap = new Map<Id, Decimal>();
        for(SBQQ__QuoteLine__c line : lines){
            quoteLineIds.add(line.Id);
            quoteLine2priceMap.put(line.Id, line.SBQQ__NetPrice__c);
            quoteLine2quantityMap.put(line.Id, line.SBQQ__Quantity__c);
        }

        List<ccrz__E_CartItem__c> affectedCartItems = [SELECT Id, Quote_Line__c, ccrz__Price__c, ccrz__Quantity__c FROM ccrz__E_CartItem__c WHERE Quote_Line__c IN :quoteLineIds];

        for(ccrz__E_CartItem__c ci : affectedCartItems){
            ci.ccrz__Price__c = quoteLine2priceMap.get(ci.Quote_Line__c);
            ci.ccrz__Quantity__c = quoteLine2quantityMap.get(ci.Quote_Line__c);
        }

        database.update(affectedCartItems);
    }

}