objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Don_Total__c</fullName>
        <label>Contract Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>SBQQ__Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract that governs this subscription.</description>
        <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__NetPrice__c</fullName>
        <description>Net price for this subscription.</description>
        <inlineHelpText>Net price for this subscription.</inlineHelpText>
        <label>Net Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PriceAdjusterController.cls
public with sharing class PriceAdjusterController {

    @AuraEnabled
    public static Contract[] getActiveContracts(){
        // System.debug('getAccountContracts accountId' + accountId);
        Contract[] contracts = [
            SELECT Id, AccountId, Account.Name, Account.BillingAddress, ContractNumber, StartDate, EndDate, ContractTerm, Status 
            FROM Contract 
            WHERE Status = 'Activated'];
        System.debug(contracts);
        return contracts;
    }


    @AuraEnabled
    public static void submitForPriceAdjustment(String productFamily, String billingCountry, Decimal adjustment){
        try {
            Contract[] contracts = [
            SELECT Id, AccountId, Account.Name, Account.BillingAddress, ContractNumber, StartDate, EndDate,
                    ContractTerm, Status, SBQQ__Quote__c, Don_Total__c
            FROM Contract
            WHERE Status = 'Activated' AND Account.BillingCountry = :billingCountry AND (NOT Account.Name like 'Acme%')];

            SBQQ__Subscription__c[] subscriptions = new List<SBQQ__Subscription__c>();

            for(Contract contract : contracts){
                subscriptions = [
                    SELECT Id, SBQQ__Product__c, SBQQ__NetPrice__c, SBQQ__Product__r.family 
                    FROM SBQQ__Subscription__c
                    Where SBQQ__Contract__c = :contract.Id
                ];

                for(SBQQ__Subscription__c subscription : subscriptions)
                {
                    if(subscription.SBQQ__Product__r.family == productFamily)
                    {
                        subscription.SBQQ__NetPrice__c = subscription.SBQQ__NetPrice__c + (subscription.SBQQ__NetPrice__c * (adjustment/100));
                        update subscription;
                        System.debug('updated Sub : ' + subscription);
                    }
                }
                if(contract.Don_Total__c != null)
                {
                    contract.Don_Total__c = contract.Don_Total__c + (contract.Don_Total__c * (adjustment/100));    
                    update contract;
                    System.debug('updated Contract : ' + contract.Don_Total__c);    
                }
            }
            return;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}