objects/JournalSubType.object
<CustomObject>
    <fields>
        <fullName>RuleType__c</fullName>
        <label>Rule Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TransactionJournal.object
<CustomObject>
    <fields>
        <fullName>ActivityCategory__c</fullName>
        <label>Activity Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ActivityCategory</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

globalValueSets/ActivityCategory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Business Review</fullName>
    </customValue>
    <customValue>
        <fullName>Compliance</fullName>
    </customValue>
    <customValue>
        <fullName>Product Webinar</fullName>
    </customValue>
    <customValue>
        <fullName>Quiz of the day</fullName>
    </customValue>
    <customValue>
        <fullName>Quiz of the week</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Training</fullName>
    </customValue>
    <customValue>
        <fullName>Security</fullName>
    </customValue>
    <customValue>
        <fullName>Technical Knowledge</fullName>
    </customValue>
    <customValue>
        <fullName>Support Training</fullName>
    </customValue>
    <customValue>
        <fullName>App Download</fullName>
    </customValue>
    <customValue>
        <fullName>Training Workshop</fullName>
    </customValue>
    <customValue>
        <fullName>Online Training</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Yearly Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Engagement</fullName>
    </customValue>
    <customValue>
        <fullName>Member activity</fullName>
    </customValue>
    <masterLabel>Activity Category</masterLabel>
</GlobalValueSet>

classes/AccrualApexBatchScheduler.cls
global inherited sharing class AccrualApexBatchScheduler implements Schedulable,Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
  String accrualTransactionQuery;
  String journalTypeName = 'Accrual';
  String loyaltyProgramName = 'Partner Extraa Program';
  public Integer recordsProcessed = 0;
  public Integer recordsFailed = 0;

  public void setLoyaltyTestData(
    String loyaltyProgramName,
    String journalTypeName
  ) {
    this.loyaltyProgramName = loyaltyProgramName;
    this.journalTypeName = journalTypeName;
  }

  global Database.QueryLocator start(Database.BatchableContext BC) {
    return Database.getQueryLocator(this.accrualTransactionQuery);
  }

  global void execute(
    Database.BatchableContext BC,
    List<TransactionJournal> accrualTransactions
  ) {
    recordsProcessed += accrualTransactions.size();

    //Calling accrual logic on Pending accrual transactions
    AccrualApexImplementation accrualApex = new AccrualApexImplementation();
    recordsFailed += accrualApex.executeAccrualApex(accrualTransactions);
  }

  global void finish(Database.BatchableContext BC) {
    // Query the AsyncApexJob object to retrieve the current job's information.
    AsyncApexJob job = [
      SELECT
        Id,
        Status,
        NumberOfErrors,
        JobItemsProcessed,
        TotalJobItems,
        CreatedBy.Email
      FROM AsyncApexJob
      WHERE Id = :bc.getJobId()
      WITH SECURITY_ENFORCED
    ];

    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    String[] toAddresses = new List<String>{ job.CreatedBy.Email };
    mail.setToAddresses(toAddresses);
    mail.setSenderDisplayName('Accrual Batch Processing Status');
    mail.setSubject('Loyalty Sample App Accrual Batch Process Completed');
    mail.setPlainTextBody(
      'Batch Process has completed.\n Records Processed: ' +
      recordsProcessed +
      '\nRecords Failed : ' +
      recordsFailed +
      '\nThe batch Apex job processed ' +
      job.TotalJobItems +
      ' batches with ' +
      job.NumberOfErrors +
      ' batch failures.'
    );

    Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ mail });
  }

  global void execute(SchedulableContext sc) {
    //Query for all TransactionJournals which is of type Accrual and status is Pending
    this.accrualTransactionQuery =
      'SELECT Id, MemberId, Quantity, TransactionAmount, ProductId, ProductCategoryId,' +
      ' JournalType.Name, JournalSubType.Name, JournalSubType.RuleType__c, ActivityCategory__c ' +
      'FROM TransactionJournal ' +
      'WHERE LoyaltyProgram.Name = \'' +
      this.loyaltyProgramName +
      '\' AND JournalType.Name = \'' +
      this.journalTypeName +
      '\' AND Status = \'Pending\' WITH SECURITY_ENFORCED';

    //Parameters of ExecuteBatch(context,BatchSize)
    Database.executeBatch(this);
  }
}