objects/RedeemPointsProductCategory__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>LoyaltyProgramPartner</referenceTo>
        <relationshipLabel>Redeem Points Product Categories</relationshipLabel>
        <relationshipName>Redeem_Points_Product_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductCategory__c</fullName>
        <label>Product Category</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>RedeemPointsProductCategories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RedemptionType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Redemption Type</label>
        <referenceTo>JournalSubType</referenceTo>
        <relationshipLabel>Redeem Points Product Categories</relationshipLabel>
        <relationshipName>Redeem_Points_Product_Categories</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>VoucherDefinitionId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Voucher Definition</label>
        <referenceTo>VoucherDefinition</referenceTo>
        <relationshipLabel>Redeem Points Product Categories</relationshipLabel>
        <relationshipName>Redeem_Points_Product_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Redeem Points Product Category</label>
    <nameField>
        <label>Redeem Points Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Redeem Points Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RedemptionConstants.cls
/**
 * @description       : 
 * @author            : Salesforce
 * @group             : 
 * @last modified on  : 02-25-2021
 * @last modified by  : Salesforce
 * Modifications Log 
 * Ver   Date         Author       Modification
 * 1.0   02-25-2021   Salesforce   Initial Version
**/
public without sharing class RedemptionConstants {
    
    public static String CURRENTCLASSNAME  = RedemptionConstants.class.getName();
    public static Decimal APIVERSION = [SELECT ApiVersion FROM ApexClass WHERE Name = :CURRENTCLASSNAME Limit 1].ApiVersion;
    
    //Action URLs
    public static final String COMPOSITE_POST_URL = '/services/data/v'+ APIVERSION +'/composite/sobjects';
    public static final String DT_REDEMPTION_ACTION_URL = '/services/data/v'+ APIVERSION +'/actions/custom/decisionTableAction/Points_to_Redeem_Based_on_Products_and_Vouchers_Default';
    public static final String GET_POINTS_BALANCE_ACTION_URL = '/services/data/v'+ APIVERSION +'/actions/standard/getPointsBalance';
    public static final String DEBIT_POINTS_ACTION_URL = '/services/data/v'+ APIVERSION +'/actions/standard/debitPoints';
    public static final String ISSUE_VOUCHER_ACTION_URL = '/services/data/v'+ APIVERSION +'/actions/standard/issueVoucher';
    
    //Flow names, input and output variables names which are used in Redemption Execution
    public static final String REDEMPTION_FLOW_API_NAME = 'Deduct_Points_Based_on_Product_and_Vouchers';
    
    public static final Decimal TRN_LIMIT = 10;
    public static final Decimal COUNT_NEW_VOUCHERS_CREATE = 10;
    
    public static final String CHANNEL_FIELD_NAME = 'Channel';
    
    //Loyalty Program specific values
    public static final String PROGRAM_NAME = 'Partner Extraa Program';
    public static final String NQP_CURRENCY = 'Points';
    
    //Field API names for RedeemPointsProductCategory Custom Object that is used in DT
    public static final String REDEMPTION_CATALOG = 'RedeemPointsProductCategory__c';
    public static final String REDEMPTION_CATALOG_CHANNEL = 'RedemptionChannel__c';
    public static final String REDEMPTION_CATALOG_PARTNER = 'Partner__c';
    public static final String REDEMPTION_CATALOG_CATEGORY = 'ProductCategory__c';
    public static final String REDEMPTION_CATALOG_PRODUCT = 'Product__c';
    public static final String REDEMPTION_CATALOG_PROGRAM = 'LoyaltyProgram__c';
    public static final String REDEMPTION_CATALOG_START_DATE = 'StartDate__c';
    public static final String REDEMPTION_CATALOG_END_DATE = 'EndDate__c';
    public static final String REDEMPTION_CATALOG_VOUCHER_DEFINITION = 'VoucherDefinitionId__c';
    public static final String REDEMPTION_CATALOG_REDEMPTION_TYPE = 'RedemptionType__c';
    public static final String REDEMPTION_CATALOG_POINTS = 'Points__c';
    
    enum REDEMPTION_TYPE {Product, Voucher}
    public static final Id PRODUCT_SUBTYPE_ID = [SELECT Id FROM JournalSubType WHERE Name = :REDEMPTION_TYPE.Product.name() LIMIT 1].Id;
    public static final Id VOUCHER_SUBTYPE_ID = [SELECT Id FROM JournalSubType WHERE Name = :REDEMPTION_TYPE.Voucher.name() LIMIT 1].Id;
  
}