objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__PricebookId__c</fullName>
        <description>ID of the Price Book used by this quote.</description>
        <inlineHelpText>ID of the Price Book used by this quote.</inlineHelpText>
        <label>Pricebook ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
        <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionTerm__c</fullName>
        <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
        <inlineHelpText>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</inlineHelpText>
        <label>Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Type__c</fullName>
        <description>Indicates the type of quote.</description>
        <inlineHelpText>Indicates the type of quote.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote</fullName>
                    <default>true</default>
                    <label>Quote</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Q2CGenerateQuickQuote.cls
public class Q2CGenerateQuickQuote {

    public static String mydomain = System.Url.getSalesforceBaseUrl().toExternalForm().substringBefore('.').substringBeforeLast('c');
    public static String instanceName = [SELECT InstanceName FROM Organization LIMIT 1].InstanceName;
    
    
// This is an Extension Controller. Thus, we must invoke the standard controller.
    public Q2CGenerateQuickQuote(ApexPages.StandardController controller) {
    }

// Method for creating Quote 
    public static PageReference genQuote() {
        
        Id acctId = ApexPages.currentPage().getParameters().get('id');
        
        //Revenue Cloud specific setup. If there's any error, check if someone renamed the Price Book and/or Opty Record Type ID
        List<RecordType> optyRecordTypeId = [SELECT Id FROM RecordType WHERE sObjectType='Opportunity' AND RecordType.name = 'Revenue Cloud' LIMIT 1];
        List<PriceBook2> PBListId = [SELECT id FROM Pricebook2 WHERE Name = 'CPQ Products' LIMIT 1];

        if(optyRecordTypeId.size() > 0 && PBListId.size() > 0){
            Opportunity opp = new Opportunity(CloseDate = Date.today(), AccountId = acctId, StageName = 'Qualification', Name = 'New Opportunity', RecordTypeId = optyRecordTypeId.get(0).id, Pricebook2Id = PBListId.get(0).id);
            Database.insert(opp);
            Id oppId = opp.Id;
            SBQQ__Quote__c q = new SBQQ__Quote__c(SBQQ__Primary__c = true, SBQQ__Account__c = acctId, SBQQ__SubscriptionTerm__c = 12, SBQQ__Opportunity2__c = oppId, SBQQ__Status__c = 'Draft', SBQQ__Type__c = 'Quote', SBQQ__PricebookId__c = PBListId.get(0).id);
            List<Contact> ContactList = [SELECT Id FROM Contact WHERE AccountId = :acctId LIMIT 1];
            if (ContactList.size() > 0) {
                q.SBQQ__PrimaryContact__c = ContactList.get(0).Id;
            }
            Database.insert(q);
            String quoteId = q.Id;
            //Returns URL and redirects the Visualforce page
            // return new PageReference(mydomain + 'sbqq.' + instanceName + '.visual.force.com/apex/sb?scontrolCaching=1&id=' + quoteId + '#quote/le?qId=' + quoteId);

            return new PageReference('/apex/sbqq__sb?scontrolCaching=1&id=' + quoteId + '#quote/le?qId=' + quoteId);
        }
        else{
            return new PageReference('/lightning/r/Account/' + acctId + '/view');
        }
    }
    public static PageReference genQuoteFromOpty() {
        
        Id oppId = ApexPages.currentPage().getParameters().get('id');
        Opportunity opty = [SELECT id, Pricebook2Id, AccountId FROM Opportunity WHERE id =: oppId LIMIT 1];
        List<PriceBook2> PBListId = [SELECT id FROM Pricebook2 WHERE id =: opty.Pricebook2Id LIMIT 1];

        SBQQ__Quote__c q = new SBQQ__Quote__c(SBQQ__Primary__c = true, SBQQ__Account__c = opty.AccountId, SBQQ__SubscriptionTerm__c = 12, SBQQ__Opportunity2__c = oppId, SBQQ__Status__c = 'Draft', SBQQ__Type__c = 'Quote', SBQQ__PricebookId__c = PBListId.get(0).id );
        List<Contact> ContactList = [SELECT Id FROM Contact WHERE AccountId = :opty.AccountId LIMIT 1];
        if (ContactList.size() > 0) {
            q.SBQQ__PrimaryContact__c = ContactList.get(0).Id;
        }
        Database.insert(q);
        String quoteId = q.Id;
        //Returns URL and redirects the Visualforce page
        // return new PageReference(mydomain + 'sbqq.' + instanceName + '.visual.force.com/apex/sb?scontrolCaching=1&id=' + quoteId + '#quote/le?qId=' + quoteId);

        return new PageReference('/apex/sbqq__sb?scontrolCaching=1&id=' + quoteId + '#quote/le?qId=' + quoteId);
    }

}