objects/VoucherCode__c.object
<CustomObject>
    <fields>
        <fullName>LoyaltyProgramMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The loyalty program member who has been issued the voucher.</description>
        <label>Loyalty Program Member</label>
        <referenceTo>LoyaltyProgramMember</referenceTo>
        <relationshipLabel>Voucher Codes</relationshipLabel>
        <relationshipName>Voucher_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SequentialCounterNumber__c</fullName>
        <description>The incremental token number associated with the voucher code.</description>
        <label>Sequential Voucher Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VoucherCodeCategory__c</fullName>
        <description>The category for which the voucher code is generated.</description>
        <label>Voucher Code Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Redemption</fullName>
                </value>
                <value>
                    <fullName>Accrual</fullName>
                </value>
                <value>
                    <fullName>Activity</fullName>
                </value>
                <value>
                    <fullName>Promotion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VoucherCodeCorrelationId__c</fullName>
        <description>The correlation ID of the voucher code category.</description>
        <label>Voucher Code Correlation ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VoucherCodeStatus__c</fullName>
        <description>The status of the voucher code.</description>
        <label>Voucher Code Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VoucherCodeType__c</fullName>
        <description>The type of code assigned to the member.</description>
        <label>Voucher Code Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Scan Code</fullName>
                </value>
                <value>
                    <fullName>Voucher Code</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VoucherCode__c</fullName>
        <description>The voucher code issued to a loyalty program member. This is derived using the voucher code prefix, voucher code suffix, and incremental/sequential voucher number.</description>
        <formula>VoucherDefinitionId__r.VoucherCodePrefix__c + TEXT( SequentialCounterNumber__c ) + VoucherDefinitionId__r.VoucherCodeSuffix__c</formula>
        <label>Voucher Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VoucherDefinitionId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The parameters that define the voucher code assigned to the member.</description>
        <label>Voucher Definition</label>
        <referenceTo>VoucherDefinition</referenceTo>
        <relationshipLabel>Voucher Codes</relationshipLabel>
        <relationshipName>Voucher_Codes1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Voucher Code</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voucher Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/VoucherDefinition.object
<CustomObject>
    <fields>
        <fullName>StartingVoucherNumber__c</fullName>
        <description>The starting number for the numeric part of the voucher code.</description>
        <label>Starting Voucher Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/VoucherCodeUtil.cls
global without sharing class VoucherCodeUtil {
    
    @InvocableMethod(label='Get Voucher Code' description='Returns the voucher code of the any first record from list of VoucherCode__c')
    public static GetVoucherCodeActionResponse[] getVoucherCode(GetVoucherCodeActionRequest[] requests){
        GetVoucherCodeActionResponse[] responses = new List<GetVoucherCodeActionResponse>();
        for ( GetVoucherCodeActionRequest getCodeRequest : requests)
        {
            GetVoucherCodeActionResponse response = new GetVoucherCodeActionResponse();
            Integer voucherCodeRecordCount = [SELECT COUNT() FROM VoucherCode__c 
                                              WHERE VoucherDefinitionId__c = :getCodeRequest.VoucherDefinitionId AND VoucherCodeStatus__c = 'New'];
            
            if (voucherCodeRecordCount == 0){
                generateNewVoucherCodes(getCodeRequest.VoucherDefinitionId, RedemptionConstants.COUNT_NEW_VOUCHERS_CREATE, getCodeRequest.isFlowCall );
            }
            VoucherCode__c voucherCodeRecord = [SELECT Id FROM VoucherCode__c 
                                                          WHERE VoucherDefinitionId__c = :getCodeRequest.VoucherDefinitionId AND VoucherCodeStatus__c = 'New' 
                                                          Limit 1 FOR UPDATE];
            
            if (voucherCodeRecord != null){
                voucherCodeRecord.VoucherCodeCategory__c = getCodeRequest.VoucherCodeCategory;
                voucherCodeRecord.VoucherCodeCorrelationId__c = getCodeRequest.VoucherCodeCategoryId;
                voucherCodeRecord.LoyaltyProgramMember__c = getCodeRequest.MemberId;
                voucherCodeRecord.VoucherCodeStatus__c = 'Processed';
                
                performDML(new List<SObject>{voucherCodeRecord}, getCodeRequest.isFlowCall, false );
                response.VoucherCode = [SELECT Id,VoucherCode__c FROM VoucherCode__c 
                                                          WHERE Id = :voucherCodeRecord.Id].VoucherCode__c;
                responses.add(response);
            } else {
                throw new GetVoucherCodeException(RedemptionErrors.ERROR_VOUCHER_CODE_UNAVAILABLE);
            }
        }
        return responses;
    }
    
    static void generateNewVoucherCodes(String voucherDefinitionId, Decimal noOfNewVouchers, Boolean isFlowCall){
        VoucherDefinition voucherDefinition = [SELECT Id,StartingVoucherNumber__c FROM VoucherDefinition 
                                                      WHERE Id = :voucherDefinitionId 
                                                      Limit 1 FOR UPDATE];
        List<VoucherCode__c> newVoucherCodeRecords = new List<VoucherCode__c>();
        for(Integer i =1; i<=noOfNewVouchers; i++){
            VoucherCode__c newVoucherCode = new VoucherCode__c();
            newVoucherCode.VoucherCodeType__c = 'Voucher Code';
            newVoucherCode.SequentialCounterNumber__c = i+voucherDefinition.StartingVoucherNumber__c;
            newVoucherCode.VoucherCodeStatus__c = 'New';
            newVoucherCode.VoucherDefinitionId__c = voucherDefinition.Id;
            newVoucherCodeRecords.add(newVoucherCode);
        }
        voucherDefinition.StartingVoucherNumber__c += noOfNewVouchers;
        performDML(newVoucherCodeRecords, isFlowCall, true);
        performDML(new List<SObject>{voucherDefinition}, isFlowCall, false);
    }
    
    global class GetVoucherCodeActionRequest {
        @InvocableVariable(label='VoucherDefinitionId' description='The voucher definition associated with the voucher code.' required=true)
        public ID VoucherDefinitionId;
        @InvocableVariable(label='VoucherCodeCorrelationId' description='The correlation ID of the voucher code category.' required=false)
        public String VoucherCodeCategoryId;
        @InvocableVariable(label='VoucherCodeCategory' description='The category for which the voucher code is generated.' required=true)
        public String VoucherCodeCategory;
        @InvocableVariable(label='MemberId' description='The loyalty program member who has been issued the voucher.' required=true)
        public ID MemberId;
        @InvocableVariable(label='Calling from Flow' description='Set to true if using in flow' required=true)
        public Boolean isFlowCall;
    }
    
    global class GetVoucherCodeActionResponse {
        @InvocableVariable(label='Voucher Code' description='Generated voucher code')
        public String VoucherCode;
    }
    
    static void performDML(SObject[] records, Boolean isFlowCall, Boolean isInsertDML ){
        if (isFlowCall){
            upsert records;
        } else{
            //For apex execution
            String dmlMethod = isInsertDML?'POST':'PATCH';
            Database.SaveResult[] dmlResults = RedemptionRestUtil.performBulksObjectOperation(dmlMethod, records);
            for (Database.SaveResult dmlResult : dmlResults ){
                if (!dmlResult.isSuccess()){
                    throw new GetVoucherCodeException(RedemptionErrors.ERROR_VOUCHER_CODE_UNAVAILABLE);
                } 
            }
        } 
    }

    //Custom Exception class to throw errors occurred during GenerateVoucherCode action
    public class GetVoucherCodeException extends Exception {}

}